### PR TITLE
Add support for target `x86_64h-apple-darwin`

### PR DESCRIPTION
**Pull request by NobodyXu**
https://doc.rust-lang.org/nightly/rustc/platform-support/x86_64h-apple-darwin.html

### CODE REVIEW

**Comment by NobodyXu** [comment]
@sunfishcode Hello, can you review this PR please?
We recently added support for `x86_64h-apple-darwin` in `cargo-binstall` but since target-lexicon isn't able to parse this target it causes an error in our application

https://github.com/cargo-bins/cargo-binstall/pull/1228

**Comment by NobodyXu** [comment]
@bjorn3 @sunfishcode Friendly pinging as this PR has been stale for at least one week.

**Comment by sunfishcode** [comment]
Thanks!

**Comment by sunfishcode** [comment]
This is now released in target-lexicon 0.12.11.

**Pull request merged**
